default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      # This one replaces github.com/dnephin/pre-commit-golang's
      # go-mod-tidy hook because it only works with top-level
      # go.mod/go.sum file
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: tools/go-mod-tidy
        files: '\.go$'
        language: script

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/schmir-at-bb/gci
    rev: "9283498f6ee8b0be960df5bf6bca058422eb971b"
    hooks:
      - id: gci
        args: ["-local", "shielder"]
        exclude: ^shuttermint/contract/binding\.go|shuttermint/shmsg/.*\.pb\.go|shuttermint/shcryptowasm/.*_wasm\.go$

  - repo: https://github.com/schmir-at-bb/gofumpt
    rev: "45be18d02b08dbeeb38ce0b092ba41fef322b482"
    hooks:
      - id: gofumpt
        exclude: ^shuttermint/contract/binding\.go|shuttermint/shmsg/.*\.pb\.go$

  # CircleCI stop here

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        additional_dependencies:
          ["prettier@2.2.1", "prettier-plugin-solidity@1.0.0-beta.5"]
        args: ["--plugin=prettier-plugin-solidity"]
        exclude: "^contracts/openzeppelin/.*"

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/sqlalchemyorg/zimports
    rev: cfdf326902fe8e4478d11a7cb2e837bab1cde1d0
    hooks:
      - id: zimports

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["contracts/tests/", "noxfile.py"]
        pass_filenames: False
